<?= view('Modules\InventarioEquipamentos\Views\templates\headerTemplate', [
    'title'=>lang('InventarioEquipamentos.home'),
]) ?>

<section>

    <h1>Lorem Ipsum:</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus euismod in lacus id tincidunt. Proin diam neque, dapibus vitae justo eget, maximus porttitor turpis. Maecenas vulputate cursus egestas. Aliquam aliquet urna a ante scelerisque scelerisque. Mauris sapien metus, consequat at posuere ac, vulputate sed metus. Pellentesque sit amet lorem finibus, ultrices quam at, commodo massa. Suspendisse consectetur nisi urna, et pharetra purus viverra quis. Nullam velit neque, feugiat et interdum quis, bibendum at eros. Ut blandit arcu varius, condimentum nulla at, aliquam quam. Ut euismod, est ac eleifend porttitor, nibh dolor tempus lectus, nec porttitor ligula massa nec tortor. Nulla et dapibus velit, a pellentesque elit. Suspendisse eu mi mollis, semper mauris a, pellentesque felis. Maecenas lacinia, nunc a feugiat rhoncus, enim eros congue odio, eget malesuada risus lacus in erat. Donec sodales scelerisque nibh.</p>
    <p>Ut nec lacus cursus, consectetur purus vitae, mattis sem. Sed mollis interdum nisi, at blandit sem tempor in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque eget libero ex. Suspendisse a velit dapibus, porta tellus quis, sollicitudin orci. Nunc quis malesuada urna. Aenean tincidunt mi eu fringilla aliquet. Curabitur tristique ac libero quis blandit. Nulla eu rhoncus arcu. In eu dignissim diam, aliquam condimentum turpis. Nulla at tempor nisl. Nullam at odio eget augue rhoncus ullamcorper. Curabitur pretium tincidunt velit nec posuere. Nulla facilisi. Sed eu enim id diam finibus posuere. Phasellus sit amet mauris pellentesque lacus bibendum volutpat non iaculis mauris.</p>
    <p>Vestibulum eget metus ac magna laoreet laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pretium scelerisque leo, et mollis mi tincidunt hendrerit. Cras ante justo, ornare sit amet justo vitae, viverra ornare nisi. Donec congue venenatis faucibus. Nunc lorem nisi, tempor at ipsum in, imperdiet iaculis lorem. Cras scelerisque massa magna, et fringilla ligula luctus eget. Etiam et pretium mi. Quisque molestie est eget mattis mattis. Nam egestas, erat quis tincidunt dictum, nisi velit pretium massa, nec vulputate tellus sem a erat. Vestibulum ut nisl sit amet nunc euismod sodales at blandit odio.</p>
    <p>Morbi a eleifend purus, ut egestas orci. Vestibulum rutrum dictum arcu, eget finibus nibh bibendum eget. Cras gravida est et eros lobortis, eu feugiat nisi porta. Phasellus vitae dolor pharetra, tincidunt ipsum at, sagittis risus. Vestibulum porttitor placerat diam sed finibus. Nullam ultricies vestibulum lacus at bibendum. Integer ultricies nulla in mauris posuere commodo. Cras sit amet pulvinar ante, maximus finibus tortor. Integer odio risus, hendrerit at quam a, mollis commodo arcu. Morbi et neque tempor, vestibulum odio ac, aliquet mauris. Donec iaculis odio vel arcu ornare dapibus.</p>
    <p>Donec placerat est vel mi scelerisque, vitae lobortis turpis interdum. Fusce sed ligula suscipit, rhoncus elit vitae, egestas nibh. Proin semper, est interdum rutrum feugiat, justo elit imperdiet dui, sed semper libero ex vel nibh. Phasellus eget elementum orci. Etiam hendrerit lacinia sem, quis sagittis tellus tincidunt sed. Cras nec libero nibh. Sed ullamcorper augue bibendum urna cursus eleifend.</p>

</section>

<?= view('Modules\InventarioEquipamentos\Views\templates\footerTemplate') ?>